### ISSUE TITLE
Propagate response from PyPI Observations API

### ISSUE THREAD

**Issue by Robin5605** [vipyrsec/dragonfly-reporter#23]
Currently the method that wraps the `httpx.post` to the Observations API does not actually check the response code, so even if we get a non-200, the endpoint will register this as success and return 200 OK:
https://github.com/vipyrsec/dragonfly-reporter/blob/d622aef594532998309ff48aa8bb3374bfcc0684/src/reporter/pypi_client.py#L34-L38

This could be remedied by a custom exception that represents an not-OK response from this endpoint

**Comment by miketheman** [comment]
Also see Event Hooks: https://www.python-httpx.org/advanced/event-hooks/
